In [1]:
import pandas as pd
from bertopic import BERTopic
df18 = pd.read_csv(
    r"C:\Projects\worldcup-social-media-nlp\results\worldcup2018_bertopic_topics.csv"
)

topic_info18 = pd.read_csv(
    r"C:\Projects\worldcup-social-media-nlp\results\worldcup2018_bertopic_topic_info.csv"
)

df22 = pd.read_csv(
    r"C:\Projects\worldcup-social-media-nlp\results\worldcup2022_bertopic_topics.csv"
)

topic_info22 = pd.read_csv(
    r"C:\Projects\worldcup-social-media-nlp\results\worldcup2022_bertopic_topic_info.csv"
)

topic_model18 = BERTopic.load(
    r"C:\Projects\worldcup-social-media-nlp\models\worldcup2018_bertopic"
)

topic_model22 = BERTopic.load(
    r"C:\Projects\worldcup-social-media-nlp\models\worldcup2022_bertopic"
)

In [68]:
topic_info18.head(20)

,Topic,Count,Name,Representation,Representative_Docs
0,-1,46485,-1_match_belgium_team_england,"['match', 'belgium', 'team', 'england', 'watch...","['france win today match', 'mbappe world champ..."
1,0,1621,0_russian_russia_moscow_putin,"['russian', 'russia', 'moscow', 'putin', 'host...","['russia win', 'well done russian great see', ..."
2,1,679,1_shootout_penalty_dramatic_two,"['shootout', 'penalty', 'dramatic', 'two', 'ne...","['penalty shootout', 'penalty shootout', 'pena..."
3,2,600,2_home_coming_door_vacation,"['home', 'coming', 'door', 'vacation', 'going'...","['coming home v', 'coming home coming home', '..."
4,3,569,3_africa_african_continent_south,"['africa', 'african', 'continent', 'south', 's...","['team africa', 'say africa world still africa..."
5,4,520,4_beer_drink_food_pub,"['beer', 'drink', 'food', 'pub', 'lunch', 'sna...","['someone get keeper beer', 'take beer back', ..."
6,5,511,5_colombia_colombian_columbia_dirty,"['colombia', 'colombian', 'columbia', 'dirty',...","['colombia england england penalty shootout', ..."
7,6,511,6_semi_final_semifinal_began,"['semi', 'final', 'semifinal', 'began', 'tonig...","['semi final', 'semi final', 'semi final v']"
8,7,475,7_messi_lionel_greatest_cr,"['messi', 'lionel', 'greatest', 'cr', 'prove',...","['messi', 'messi', 'messi']"
9,8,448,8_croatian_congrats_deserve_proud,"['croatian', 'congrats', 'deserve', 'proud', '...",['croatia great great worldcup congrats well d...
10,9,447,9_shootout_penalty_dramatic_qf,"['shootout', 'penalty', 'dramatic', 'qf', 'cro...","['croatia win shootout', 'croatia win penalty ..."
11,10,439,10_denmark_penalty_shootout_croatia,"['denmark', 'penalty', 'shootout', 'croatia', ...","['croatia win penalty denmark', 'penalty croat..."
12,11,414,11_immigrant_migrant_immigration_racism,"['immigrant', 'migrant', 'immigration', 'racis...",['dear team member muslim immigrant child immi...
13,12,389,12_argentina_france_argentine_tick,"['argentina', 'france', 'argentine', 'tick', '...","['france argentina game', 'france argentina fr..."
14,13,389,13_schmeichel_kasper_schmeichels_subasic,"['schmeichel', 'kasper', 'schmeichels', 'subas...","['man match kasper schmeichel', 'feel kasper s..."
15,14,383,14_bleu_le_allez_blue,"['bleu', 'le', 'allez', 'blue', 'devil', 'alle...","['fifa world cup winner allez le bleu', 'allez..."
16,15,359,15_tournament_tourney_ashamed_doug,"['tournament', 'tourney', 'ashamed', 'doug', '...","['tournament', 'tournament', 'tournament']"
17,16,357,16_denmark_danish_unlucky_gutted,"['denmark', 'danish', 'unlucky', 'gutted', 'de...","['denmark', 'denmark', 'denmark']"
18,17,354,17_nigeria_nigerian_naija_argentina,"['nigeria', 'nigerian', 'naija', 'argentina', ...","['beat nigeria win world cup', 'nigeria say ar..."
19,18,337,18_denmark_danish_cruel_dane,"['denmark', 'danish', 'cruel', 'dane', 'croati...","['croatia v denmark game', 'game croatia denma..."

In [69]:
topic_info18.count()

Topic                  1295
Count                  1295
Name                   1295
Representation         1295
Representative_Docs    1295
dtype: int64

In [70]:
topic_info22.count()

Topic                  271
Count                  271
Name                   271
Representation         271
Representative_Docs    271
dtype: int64

In [71]:
topic_info22.head(20)

,Topic,Count,Name,Representation,Representative_Docs
0,-1,11006,-1_worldcup_qatar_game_worldcup2022,"['worldcup', 'qatar', 'game', 'worldcup2022', ...","[""['good', 'time', 'first', 'game', 'worldcup2..."
1,0,585,0_jungkook_jungkookatfifaworldcup_dreamersbyju...,"['jungkook', 'jungkookatfifaworldcup', 'dreame...","[""['thank', 'amazing', 'performance', 'jungkoo..."
2,1,516,1_qatarworldcup2022_qatar2022_qatar_ready,"['qatarworldcup2022', 'qatar2022', 'qatar', 'r...","[""['go', 'worldcup', 'fifaworldcup', 'qatarwor..."
3,2,335,2_var_decision_ruin_already,"['var', 'decision', 'ruin', 'already', 'minute...","[""['var', 'worldcup2022']"", ""['var', 'worldcup..."
4,3,307,3_human_migrant_worker_hypocrisy,"['human', 'migrant', 'worker', 'hypocrisy', 'r...","[""['worldcup2022', 'get', 'underway', 'qatar',..."
5,4,277,4_offside_rule_call_explain,"['offside', 'rule', 'call', 'explain', 'defend...","[""['offside', 'worldcup', 'worldcup2022']"", ""[..."
6,5,253,5_ecuador_robbed_ecuadorvsqatar_header,"['ecuador', 'robbed', 'ecuadorvsqatar', 'heade...","[""['ecuador', 'worldcup2022']"", ""['ecuador', '..."
7,6,250,6_right_feel_people_enjoy,"['right', 'feel', 'people', 'enjoy', 'human', ...","[""['wondering', 'soccer', 'fan', 'feel', 'espe..."
8,7,190,7_openingceremony_ceremony_online_fifa,"['openingceremony', 'ceremony', 'online', 'fif...","[""['2022', 'fifa', 'world', 'cup', 'opening', ..."
9,8,182,8_valencia_enner_ecuador_goal,"['valencia', 'enner', 'ecuador', 'goal', 'lead...","[""['first', 'goal', 'world', 'cup', 'winner', ..."
10,9,174,9_corruption_corrupt_already_started,"['corruption', 'corrupt', 'already', 'started'...","[""['corruption', 'worldcup2022']"", ""['corrupti..."
11,10,174,10_jiocinema_streaming_jio_app,"['jiocinema', 'streaming', 'jio', 'app', 'fix'...","[""['buffering', 'issue', 'world', 'cup', 'stre..."
12,11,172,11_valencia_enner_header_goal,"['valencia', 'enner', 'header', 'goal', 'ener'...","[""['enner', 'valencia', 'first', 'world', 'cup..."
13,12,171,12_mahsaamini_iran_islamic_iranian,"['mahsaamini', 'iran', 'islamic', 'iranian', '...","[""['mahabad', 'iran', 'hear', 'islamic', 'repu..."
14,13,168,13_bbc_bbcfootball_coverage_bbcworldcup,"['bbc', 'bbcfootball', 'coverage', 'bbcworldcu...","[""['fuck', 'worldcup2022', 'coverage', 'bbc']""..."
15,14,145,14_stadium_al_bayt_doha,"['stadium', 'al', 'bayt', 'doha', 'attend', 'k...","[""['picture', 'worldcup2022', 'opening', 'cere..."
16,15,137,15_ecuador_qatar_ecuadorvsqatar_beat,"['ecuador', 'qatar', 'ecuadorvsqatar', 'beat',...","[""['ecuador', 'worldcup2022', 'qatarworldcup20..."
17,16,135,16_offside_explain_call_someone,"['offside', 'explain', 'call', 'someone', 'qat...","[""['3', 'min', 'know', 'worldcup2022', 'rigged..."
18,17,116,17_nft_crypto_eth_airdrop,"['nft', 'crypto', 'eth', 'airdrop', 'blockchai...","[""['df', 'df', 'df', 'buy', 'dfusdt', 'dforce'..."
19,18,109,18_watching_watch_soccer_match,"['watching', 'watch', 'soccer', 'match', 'read...","[""['watching', 'world', 'cup', 'worldcup2022']..."

In [72]:
topic_model18.get_topic(1)

[('shootout', np.float64(0.032916442714445895)),
 ('penalty', np.float64(0.012633440845248513)),
 ('dramatic', np.float64(0.008504206435701074)),
 ('two', np.float64(0.0049510806526642005)),
 ('nerve', np.float64(0.004357731088530049)),
 ('drama', np.float64(0.0042174836033826765)),
 ('craziest', np.float64(0.0038555415757328495)),
 ('seen', np.float64(0.003804729610555535)),
 ('ever', np.float64(0.003753545361664736)),
 ('intense', np.float64(0.003189445170445082))]

In [73]:
topic_model22.get_topic(1)

[('qatarworldcup2022', np.float64(0.018235622689757838)),
 ('qatar2022', np.float64(0.016288826293564738)),
 ('qatar', np.float64(0.014551505763784516)),
 ('ready', np.float64(0.009459128810915207)),
 ('begin', np.float64(0.007652365799933356)),
 ('fifaworldcup2022', np.float64(0.007625381974942843)),
 ('worldcup2022', np.float64(0.007228174387958443)),
 ('worldcup', np.float64(0.007190654845494265)),
 ('fuck', np.float64(0.006899104115975035)),
 ('qatarworldcup', np.float64(0.006898583258228271))]

In [74]:
topic_model18.visualize_barchart()

In [75]:
topic_model22.visualize_barchart()

# Mannual Labeling

* worldcup 2018 dataset

In [80]:
top_topics = (
    df18["topic"]
    .value_counts()
    .head(21)
)
top_topics

topic
-1     46485
 0      1621
 1       679
 2       600
 3       569
 4       520
 5       511
 6       511
 7       475
 8       448
 9       447
 10      439
 11      414
 13      389
 12      389
 14      383
 15      359
 16      357
 17      354
 18      337
 19      337
Name: count, dtype: int64

In [81]:
#remove -1 (because in BERTopic -1 is usually the outlier topic)
top_topics = top_topics[top_topics.index != -1]
top_topics

topic
0     1621
1      679
2      600
3      569
4      520
5      511
6      511
7      475
8      448
9      447
10     439
11     414
13     389
12     389
14     383
15     359
16     357
17     354
18     337
19     337
Name: count, dtype: int64

In [82]:
for topic_id, frequency in top_topics.items():

    print(f"Topic {topic_id}")
    print(f"Frequency: {frequency}")

Topic 0
Frequency: 1621
Topic 1
Frequency: 679
Topic 2
Frequency: 600
Topic 3
Frequency: 569
Topic 4
Frequency: 520
Topic 5
Frequency: 511
Topic 6
Frequency: 511
Topic 7
Frequency: 475
Topic 8
Frequency: 448
Topic 9
Frequency: 447
Topic 10
Frequency: 439
Topic 11
Frequency: 414
Topic 13
Frequency: 389
Topic 12
Frequency: 389
Topic 14
Frequency: 383
Topic 15
Frequency: 359
Topic 16
Frequency: 357
Topic 17
Frequency: 354
Topic 18
Frequency: 337
Topic 19
Frequency: 337

In [83]:
rows = []

for topic_id, frequency in top_topics.items():

    words = [
        word
        for word, score
        in topic_model18.get_topic(topic_id)[:10]
    ]
    rows.append({
        "Topic": topic_id,
        "Frequency": frequency,
        "Words": " | ".join(words)

           
    })

summary_df = pd.DataFrame(rows)

summary_df

    Topic  Frequency                                              Words
0       0       1621  russian | russia | moscow | putin | hosting | ...
1       1        679  shootout | penalty | dramatic | two | nerve | ...
2       2        600  home | coming | door | vacation | going | hous...
3       3        569  africa | african | continent | south | senegal...
4       4        520  beer | drink | food | pub | lunch | snack | pi...
5       5        511  colombia | colombian | columbia | dirty | beat...
6       6        511  semi | final | semifinal | began | tonight | q...
7       7        475  messi | lionel | greatest | cr | prove | leo |...
8       8        448  croatian | congrats | deserve | proud | croati...
9       9        447  shootout | penalty | dramatic | qf | croatia |...
10     10        439  denmark | penalty | shootout | croatia | beat ...
11     11        414  immigrant | migrant | immigration | racism | m...
12     13        389  schmeichel | kasper | schmeichels | subasic | ...
13     12        389  argentina | france | argentine | tick | highli...
14     14        383  bleu | le | allez | blue | devil | alles | du ...
15     15        359  tournament | tourney | ashamed | doug | meyers...
16     16        357  denmark | danish | unlucky | gutted | den | sc...
17     17        354  nigeria | nigerian | naija | argentina | buhar...
18     18        337  denmark | danish | cruel | dane | croatia | de...
19     19        337  football | liking | footballed | nivia | beaut...