In [2]:
import sys
import os
sys.path.append(os.path.abspath(".."))

In [3]:
from src.NMF_pipeline import run_nmf_pipeline
#Run nmf_modeling 
datasets = [
    r"C:\Projects\worldcup-social-media-nlp\Data\Preprocessed_Data\worldcup2022.csv",
    r"C:\Projects\worldcup-social-media-nlp\Data\Preprocessed_Data\worldcup2018.csv"
]
for d in datasets:
    df, vec, model, W, H = run_nmf_pipeline(d, n_topics=50)
    feature_names = vec.get_feature_names_out()
    print("\nTop words per topic:")
    for topic_idx, topic in enumerate(H[:10]):  # limit to first 10 topics
        top_words = [feature_names[i] for i in topic.argsort()[-10:][::-1]]
        print(f"Topic {topic_idx}: {top_words}")
    print(df["dominant_topic"].value_counts().head(10))
    top_topics = df["dominant_topic"].value_counts().head(10)
    for topic_idx, count  in top_topics.items():
        topic = H[topic_idx]
        top_words = [feature_names[i] for i in topic.argsort()[-10:][::-1]]
    
        print(f"Topic {topic_idx} (Count: {count}): {top_words}")

c:\Projects\worldcup-social-media-nlp\footenv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5774.81it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

ValueError: too many values to unpack (expected 5)

In [4]:
from src.NMF_pipeline import run_nmf_pipeline

(
    df,
    vec,
    model,
    W,
    H,
    topic_labels
) = run_nmf_pipeline(
    dataset_path=r"C:\Projects\worldcup-social-media-nlp\Data\Preprocessed_Data\worldcup2022.csv",
    n_topics=50
)

In [5]:
feature_names = vec.get_feature_names_out()

top_topics = df["dominant_topic"].value_counts().head(10)

for topic_idx, count in top_topics.items():

    topic = H[topic_idx]

    top_words = [
        feature_names[i]
        for i in topic.argsort()[-10:][::-1]
    ]

    print(f"\nTopic {topic_idx} (Count: {count})")
    print(top_words)

Topic 1 (Count: 1906)
['worldcup2022', 'keeper', 'fuck', 'going', 'rigged', 'got', 'well', 'sport', 'rigged worldcup2022', 'shit']

Topic 15 (Count: 895)
['qatar', 'worldcup2022 qatar', 'qatar ecuador', 'host', 'qatar world', 'money', 'qatar qatar2022', 'cup qatar', 'qatar2022 qatar', 'qatar win']

Topic 31 (Count: 742)
['football', 'football worldcup2022', 'soccer', 'fan', 'worldcup2022 football', 'football fan', 'love', 'sport', 'fifa', 'football soccer']

Topic 10 (Count: 739)
['qatar2022', 'worldcup2022 qatar2022', 'qatar2022 worldcup2022', 'qatarworldcup2022 qatar2022', 'fifaworldcup qatar2022', 'qatar2022 qatar', 'qatar2022 qatarworldcup2022', 'qatar2022 qatecu', 'qatar qatar2022', 'qatar2022 fifaworldcup']

Topic 49 (Count: 729)
['one', 'one worldcup2022', 'watch', 'player', 'best', 'watch worldcup2022', 'know', 'thing', 'see', 'country']

Topic 47 (Count: 707)
['get', 'qatar get', 'going', 'bet', 'let get', 'hope', 'get worldcup2022', 'amp', '10', 'worldcup2022 get']

Topic 34 (Count: 668)
['england', 'iran', 'tomorrow', 'england iran', 'england worldcup2022', 'group', 'wale', 'worldcup2022 england', 'usa', 'see']

Topic 18 (Count: 631)
['worldcupqatar2022', 'worldcup2022 worldcupqatar2022', 'worldcupqatar2022 worldcup2022', 'worldcupqatar2022 worldcup', 'worldcup worldcupqatar2022', 'worldcupqatar2022 qatarworldcup2022', 'worldcup2022', 'worldcupqatar2022 qatar2022', 'worldcupqatar2022 fifaworldcup', 'worldcupqatar2022 fifaworldcup2022']

Topic 3 (Count: 623)
['ceremony', 'opening', 'opening ceremony', 'ceremony worldcup2022', 'worldcup2022 opening', 'cup opening', 'bbc', '2022 opening', 'ceremony live', 'beautiful']

Topic 48 (Count: 610)
['right', 'human', 'human right', 'right worldcup2022', 'amp', 'country', 'people', 'bbc', 'worker', 'watch']

In [6]:
import pandas as pd

rows = []

for topic_id, keywords in topic_labels.items():

    label_text = ", ".join(
        [kw for kw, score in keywords]
    )

    rows.append({
        "Topic": topic_id,
        "Label": label_text
    })

labels_df = pd.DataFrame(rows)

labels_df.head(20)

    Topic                                              Label
0      19  qatarworldcup2022, worldcup2022, fifaworldcup2...
1       9  worldcup2022, worldcupqatar2022, worldcup2022q...
2      30  worldcup2022, fifa, worldcup, fifaworldcup2022...
3      17  qatarworldcup, qatarworldcup2022, jungkookworl...
4      48  lgbtq, qatarworldcup2022, hypocrisy, lgbt, pro...
5      46  qatarworldcup2022, qatar, fifa, qatar2022, fif...
6      43  qatarworldcup, qatarworldcup2022, fifa, worldc...
7      31  qatarworldcup2022, fifa, futbol, soccer, world...
8      37  qatarworldcup2022, qatarworldcup, worldcup2022...
9      29  qatar2022worldcup, worldcup2022, fifaworldcup,...
10     16  qatarworldcup2022, ecuador, qatar, qatar2022, ...
11     27  worldcupday, qatarworldcup2022, fifaworldcup, ...
12      5  qatarworldcup2022, worldcup2022, worldcup2026,...
13      1  worldcup2022, cameroon, كأس_العالم_fifa, messi...
14      0  worldcup2022, worldcup2010, worldcupbets, worl...
15     33  qatarworldcup2022, qatari, qatar, qatar2022, p...
16     42  qatarworldcup, qatarworldcup2022, qatar, qatar...
17     36  fifa22, fifaclubworldcup, fifawomensworldcup, ...
18     35  requestabet, cricket, support, available, tele...
19     11  qatarworldcup2022, fifaworldcup, qatarfans, fi...

In [7]:
from src.NMF_pipeline import run_nmf_pipeline

(
    df,
    vec,
    model,
    W,
    H,
    topic_labels
) = run_nmf_pipeline(
    dataset_path=r"C:\Projects\worldcup-social-media-nlp\Data\Preprocessed_Data\worldcup2018.csv",
    n_topics=50
)

In [8]:
feature_names = vec.get_feature_names_out()

top_topics = df["dominant_topic"].value_counts().head(10)

for topic_idx, count in top_topics.items():

    topic = H[topic_idx]

    top_words = [
        feature_names[i]
        for i in topic.argsort()[-10:][::-1]
    ]

    print(f"\nTopic {topic_idx} (Count: {count})")
    print(top_words)

Topic 49 (Count: 48648)
['match', 'like', 'man', 'man match', 'mbappe', 'retweet', 'today', 'president', 'mbappe like', 'who']

Topic 45 (Count: 31436)
['england', 'right', 'come', 'fan', 'england fan', 'paris', 'come england', 'scene', 'belgium', 'scene paris']

Topic 40 (Count: 22254)
['one', 'year', 'last', 'thing', 'making', 'one thing', 'year making', 'second year', 'last year', 'doubt']

Topic 0 (Count: 22174)
['dear france', 'cut racism', 'african cut', 'team african', 'france congratulation', 'cut', 'racism', 'congratulation winning', 'xenophobi', 'racism xenophobi']

Topic 29 (Count: 21139)
['croatia', 'denmark', 'croatia denmark', 'russia', 'russia croatia', 'france croatia', 'croatia win', 'uruguay', 'russia uruguay', 'denmark croatia']

Topic 14 (Count: 18316)
['win', 'win golden', 'france win', 'win penalty', 'croatia win', 'team win', 'win world', 'win second', 'france', 'country win']

Topic 15 (Count: 18027)
['penalty', 'save', 'shootout', 'penalty shootout', 'save penalty', 'extra time', 'extra', 'penalty extra', 'knocked', 'shootout still']

Topic 3 (Count: 17103)
['world', 'cup', 'world cup', 'fifa world', 'cup final', 'cup winner', 'cup champion', 'win world', 'champion congratulation', 'cup quarter']

Topic 37 (Count: 16538)
['time', 'watch', 'better', 'second', 'second time', 'every time', 'get better', 'every', 'get', 'time watch']

Topic 26 (Count: 16299)
['game', 'game congratulation', 'congratulation reaching', 'marcos', 'commiseration marcos', 'final commiseration', 'reaching quarter', 'commiseration', 'reaching', 'missing game']

In [11]:
import pandas as pd

rows = []

for topic_id, keywords in topic_labels.items():

    label_text = ", ".join(
        [kw for kw, score in keywords]
    )

    rows.append({
        "Topic": topic_id,
        "Label": label_text
    })
    

labels_df = pd.DataFrame(rows)

labels_df.head(20)

    Topic                                              Label
0      15  goalkeeper, penalty, schmeichels, schmeichel, ...
1      26          napoli, cavani, mandzukics, goalie, spain
2      12                power, stronger, turn, lyric, genre
3      42           knockout, stage, eliminated, fifa, final
4      31  schmeichel, keeper, christensen, taribo, socce...
5      40             puma, unicef, fifa, brazilian, manager
6      18           spain, portugal, ronaldo, fifa, fabregas
7       3            messi, ronaldo, fifa, brazil, argentina
8      43      stadium, juventus, worldcup, coutinho, neymar
9      28         argentina, portugal, messi, ronaldo, spain
10     45    england, argentina, colombia, uruguay, maradona
11     49              mbappe, messi, ronaldo, crowd, soccer
12     17                    japan, reach, anime, past, turn
13     27                 lebron, mexico, nba, samurai, pero
14     16                worldcup, colombia, lose, ball, por
15      0  lightsaber, poweeeer, poweeeeer, poweeeeeeer, ...
16     10                    soldier, mask, ali, gas, france
17     22              goalkeeper, messi, penalty, gea, kick
18     14            spain, croatia, putin, worldcup, brazil
19     11         colombia, fifa, scared, ramos, celebration