In [1]:
import pandas as pd
worldcup2018=pd.read_csv(r"C:\Projects\worldcup-social-media-nlp\Data\worldcup2018_clean.csv",na_filter=False,delimiter=',')
worldcup2022=pd.read_csv(r"C:\Projects\worldcup-social-media-nlp\Data\worldcup2022_clean.csv",na_filter=False, delimiter=',')

In [2]:
worldcup2018.head(5)

,Date,Source,Orig_Tweet,Tweet,Likes,RTs,Hashtags,Place
0,2018-07-02 01:35:45,twitter for android,rt @squawka: only two goalkeepers have saved t...,only two goalkeepers have saved three penaltie...,0,477,"worldcup,por,eng",accra
1,2018-07-02 01:35:44,twitter for android,rt @fcbarcelona: ?? @ivanrakitic scores the wi...,scores the winning penalty to send into the qu...,0,1031,worldcup,bogor
2,2018-07-02 01:35:42,twitter for android,rt @javierfernandez: tonight we have big game....,tonight we have big game,0,488,worldcup,
3,2018-07-02 01:35:41,twitter web client,we get stronger\r\nturn the music up now\r\nwe...,we get stronger turn the music up now we got t...,0,0,"powerbyexo,worldcup,fifastadiumdj,xiuminleague","zapopan, jalisco"
4,2018-07-02 01:35:40,twitter for android,rt @squawka: only two goalkeepers have saved t...,only two goalkeepers have saved three penaltie...,0,477,"worldcup,por,eng",

In [3]:
worldcup2022.head(10)

,Unnamed: 0,Date Created,Number of Likes,Source of Tweet,Tweet,Sentiment
0,0,2022-11-20 23:59:21+00:00,4,twitter web app,what are we drinking today @tucantribe \n@madb...,neutral
1,1,2022-11-20 23:59:01+00:00,3,twitter for iphone,amazing @canadasocceren #worldcup2022 launch ...,positive
2,2,2022-11-20 23:58:41+00:00,1,twitter for iphone,worth reading while watching #worldcup2022 htt...,positive
3,3,2022-11-20 23:58:33+00:00,1,twitter web app,golden maknae shinning bright\n\nhttps://t.co/...,positive
4,4,2022-11-20 23:58:28+00:00,0,twitter for android,"if the bbc cares so much about human rights, h...",negative
5,5,2022-11-20 23:57:32+00:00,0,twitter for android,"and like, will the mexican fans be able to scr...",negative
6,6,2022-11-20 23:57:06+00:00,0,twitter for android,look like a only me and the jamaican football ...,neutral
7,7,2022-11-20 23:57:05+00:00,0,twitter for android,really? football on a monday morning at 9 and ...,negative
8,8,2022-11-20 23:56:10+00:00,1,twitter for iphone,"as the world cup starts in qatar, it’s black a...",positive
9,9,2022-11-20 23:56:08+00:00,0,twitter for iphone,#worldcup2022 @itvsport &amp; @lfsystemmusic g...,positive

In [4]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [5]:
from src.nlp_preprocessing import clean_noise
import re

punct_rows = worldcup2018[worldcup2018['Orig_Tweet'].str.contains(r'[^\w\s]', regex=True, na=False)]
remove_orig_tweet_noise = punct_rows[['Orig_Tweet']].head(5).copy()

remove_orig_tweet_noise['cleaned_Orig_Tweet'] = remove_orig_tweet_noise['Orig_Tweet'].apply(clean_noise)

remove_orig_tweet_noise

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

,Orig_Tweet,cleaned_Orig_Tweet
0,rt @squawka: only two goalkeepers have saved t...,rt only two goalkeepers have saved three penal...
1,rt @fcbarcelona: ?? @ivanrakitic scores the wi...,rt scores the winning penalty to send into the...
2,rt @javierfernandez: tonight we have big game....,rt tonight we have big game worldcup
3,we get stronger\r\nturn the music up now\r\nwe...,we get stronger turn the music up now we got t...
4,rt @squawka: only two goalkeepers have saved t...,rt only two goalkeepers have saved three penal...

In [4]:
from src.nlp_preprocessing import clean_noise
qmark_rows = worldcup2018[worldcup2018['Hashtags'].str.contains(r'\?{2,}', regex=True, na=False)]
sample_noise = qmark_rows[['Hashtags']].head(5).copy()

sample_noise['cleaned_Hashtags'] = sample_noise['Hashtags'].apply(clean_noise)

sample_noise

,Hashtags,cleaned_Hashtags
91,"fifastadiumdj,worldcup,exo,??",fifastadiumdj worldcup exo
94,"worldcup,fifastadiumdj,dafbama2018exo,??,exo",worldcup fifastadiumdj dafbama2018exo exo
113,"exo,exo,??,fifastadiumdj,worldcup",exo exo fifastadiumdj worldcup
132,"powerbyexo,exo,??,fifastadiumdj,copa2018,worldcup",powerbyexo exo fifastadiumdj copa2018 worldcup
146,"powerbyexo,exo,??,fifastadiumdj,copa2018,worldcup",powerbyexo exo fifastadiumdj copa2018 worldcup

In [5]:
from src.nlp_preprocessing import clean_noise
import re

punct_rows = worldcup2022[worldcup2022['Tweet'].str.contains(r'[^\w\s]', regex=True, na=False)]
sample_noise = punct_rows[['Tweet']].head(5).copy()

sample_noise['cleaned_Tweet'] = sample_noise['Tweet'].apply(clean_noise)

sample_noise

,Tweet,cleaned_Tweet
0,what are we drinking today @tucantribe \n@madb...,what are we drinking today worldcup2022
1,amazing @canadasocceren #worldcup2022 launch ...,amazing worldcup2022 launch video shows how mu...
2,worth reading while watching #worldcup2022 htt...,worth reading while watching worldcup2022
3,golden maknae shinning bright\n\nhttps://t.co/...,golden maknae shinning bright jeonjungkook jun...
4,"if the bbc cares so much about human rights, h...",if the bbc cares so much about human rights ho...

**Tokenization**

In [6]:
# Apply tokenization to worldcup2022 tweet column
from src.nlp_preprocessing import tokenization
tweet22_tokens = sample_noise['cleaned_Tweet'].iloc[4]  
tokens = tokenization(tweet22_tokens)  
print(tokens)

['if', 'the', 'bbc', 'cares', 'so', 'much', 'about', 'human', 'rights', 'homosexual', 'rights', 'and', 'women', 'rights', 'then', 'why', 'not', 'say', 'these', 'before', 'the', 'opening', 'ceremony', 'why', 'are', 'they', 'saying', 'these', 'during', 'the', 'opening', 'ceremony', 'why', 'did', 'the', 'bbc', 'censor', 'the', 'worldcup2022', 'opening', 'ceremony']

In [7]:
# Apply tokenization to worldcup2018 orig_tweet column
from src.nlp_preprocessing import tokenization
orig_tweet_tokens = remove_orig_tweet_noise['cleaned_Orig_Tweet'].iloc[3]
tokens_orgTweet=tokenization(orig_tweet_tokens)
print(tokens_orgTweet)

['we', 'get', 'stronger', 'turn', 'the', 'music', 'up', 'now', 'we', 'got', 'that', 'power', 'power', 'powerbyexo', 'worldcup', 'fifastadiumdj', 'xiuminleague']

**Stop_words Removal**

In [8]:
#StopWords removal on Worldcup2022
from src.nlp_preprocessing import stopwords_removal
filtred_tweet22=stopwords_removal(tokens)
print ("tweet before stop words removal",tokens)
print("tweet After stop words removal",filtred_tweet22)

tweet before stop words removal ['if', 'the', 'bbc', 'cares', 'so', 'much', 'about', 'human', 'rights', 'homosexual', 'rights', 'and', 'women', 'rights', 'then', 'why', 'not', 'say', 'these', 'before', 'the', 'opening', 'ceremony', 'why', 'are', 'they', 'saying', 'these', 'during', 'the', 'opening', 'ceremony', 'why', 'did', 'the', 'bbc', 'censor', 'the', 'worldcup2022', 'opening', 'ceremony']
tweet After stop words removal ['bbc', 'cares', 'much', 'human', 'rights', 'homosexual', 'rights', 'women', 'rights', 'say', 'opening', 'ceremony', 'saying', 'opening', 'ceremony', 'bbc', 'censor', 'worldcup2022', 'opening', 'ceremony']

In [9]:
#StopWords removal on Worldcup2018
from src.nlp_preprocessing import stopwords_removal
filtred_orgtweet18=stopwords_removal(tokens_orgTweet)
print ("tweet before stop words removal",tokens_orgTweet)
print("tweet After stop words removal",filtred_orgtweet18)

tweet before stop words removal ['we', 'get', 'stronger', 'turn', 'the', 'music', 'up', 'now', 'we', 'got', 'that', 'power', 'power', 'powerbyexo', 'worldcup', 'fifastadiumdj', 'xiuminleague']
tweet After stop words removal ['get', 'stronger', 'turn', 'music', 'got', 'power', 'power', 'powerbyexo', 'worldcup', 'fifastadiumdj', 'xiuminleague']

**lemmatization**

In [ ]:
#worldcup2022
from src.nlp_preprocessing import lemmatization
lemmetized_tweet=lemmatization(filtred_tweet22)
print(lemmetized_tweet)

['bbc', 'care', 'much', 'human', 'right', 'homosexual', 'right', 'woman', 'right', 'say', 'opening', 'ceremony', 'saying', 'opening', 'ceremony', 'bbc', 'censor', 'worldcup2022', 'opening', 'ceremony']

In [12]:
#worldcup2018
from src.nlp_preprocessing import lemmatization
lemmetized_tweet=lemmatization(filtred_orgtweet18)
print(lemmetized_tweet)

['get', 'stronger', 'turn', 'music', 'got', 'power', 'power', 'powerbyexo', 'worldcup', 'fifastadiumdj', 'xiuminleague']

In [20]:
from src.nlp_preprocessing import preprocess_text
row_text=worldcup2018['Tweet'].iloc[10]
preprocessed_row=preprocess_text(row_text)
print(preprocessed_row)

['idek', 'anymore', 'spain', 'portugal']

**Preprocess all the text columns in the datasets**

In [6]:
#Apply Preprocessing on str column of worldcup2018 dataset
from src.nlp_preprocessing import preprocess_text
for col in worldcup2018.select_dtypes(include='str').columns:
    worldcup2018[col] = worldcup2018[col].fillna('').apply(preprocess_text)

In [7]:
worldcup2018.head(5)

,Date,Source,Orig_Tweet,Tweet,Likes,RTs,Hashtags,Place
0,"[2018, 07, 02, 01, 35, 45]","[twitter, android]","[rt, two, goalkeeper, saved, three, penalty, w...","[two, goalkeeper, saved, three, penalty, penal...",0,477,"[worldcup, por, eng]",[accra]
1,"[2018, 07, 02, 01, 35, 44]","[twitter, android]","[rt, score, winning, penalty, send, worldcup, ...","[score, winning, penalty, send, quarter, final...",0,1031,[worldcup],[bogor]
2,"[2018, 07, 02, 01, 35, 42]","[twitter, android]","[rt, tonight, big, game, worldcup]","[tonight, big, game]",0,488,[worldcup],[]
3,"[2018, 07, 02, 01, 35, 41]","[twitter, web, client]","[get, stronger, turn, music, got, power, power...","[get, stronger, turn, music, got, power, power]",0,0,"[powerbyexo, worldcup, fifastadiumdj, xiuminle...","[zapopan, jalisco]"
4,"[2018, 07, 02, 01, 35, 40]","[twitter, android]","[rt, two, goalkeeper, saved, three, penalty, w...","[two, goalkeeper, saved, three, penalty, penal...",0,477,"[worldcup, por, eng]",[]

In [8]:
# Join tokens for all string columns
for col in worldcup2018.select_dtypes(include='str').columns:
    worldcup2018[col] = worldcup2018[col].apply(lambda x: ' '.join(x) if isinstance(x, list) else x)

In [10]:
worldcup2018.head(5)

,Date,Source,Orig_Tweet,Tweet,Likes,RTs,Hashtags,Place
0,"[2018, 07, 02, 01, 35, 45]","[twitter, android]","[rt, two, goalkeeper, saved, three, penalty, w...","[two, goalkeeper, saved, three, penalty, penal...",0,477,"[worldcup, por, eng]",[accra]
1,"[2018, 07, 02, 01, 35, 44]","[twitter, android]","[rt, score, winning, penalty, send, worldcup, ...","[score, winning, penalty, send, quarter, final...",0,1031,[worldcup],[bogor]
2,"[2018, 07, 02, 01, 35, 42]","[twitter, android]","[rt, tonight, big, game, worldcup]","[tonight, big, game]",0,488,[worldcup],[]
3,"[2018, 07, 02, 01, 35, 41]","[twitter, web, client]","[get, stronger, turn, music, got, power, power...","[get, stronger, turn, music, got, power, power]",0,0,"[powerbyexo, worldcup, fifastadiumdj, xiuminle...","[zapopan, jalisco]"
4,"[2018, 07, 02, 01, 35, 40]","[twitter, android]","[rt, two, goalkeeper, saved, three, penalty, w...","[two, goalkeeper, saved, three, penalty, penal...",0,477,"[worldcup, por, eng]",[]

In [11]:
#save the preprocessed worldcup2018 dataset
worldcup2018.to_csv(r"C:\Projects\worldcup-social-media-nlp\Data\Preprocessed_Data\worldcup2018.csv")

In [ ]:
#Apply Preprocessing on str column of worldcup2022 dataset
from src.nlp_preprocessing import preprocess_text
for col in worldcup2022.select_dtypes(include='str').columns:
    worldcup2022[col] = worldcup2022[col].fillna('').apply(preprocess_text)

In [20]:
worldcup2022.head(5)

,Unnamed: 0,Date Created,Number of Likes,Source of Tweet,Tweet,Sentiment
0,0,"[2022, 11, 20, 23, 59, 21, 00, 00]",4,"[twitter, web, app]","[drinking, today, worldcup2022]",[neutral]
1,1,"[2022, 11, 20, 23, 59, 01, 00, 00]",3,"[twitter, iphone]","[amazing, worldcup2022, launch, video, show, m...",[positive]
2,2,"[2022, 11, 20, 23, 58, 41, 00, 00]",1,"[twitter, iphone]","[worth, reading, watching, worldcup2022]",[positive]
3,3,"[2022, 11, 20, 23, 58, 33, 00, 00]",1,"[twitter, web, app]","[golden, maknae, shinning, bright, jeonjungkoo...",[positive]
4,4,"[2022, 11, 20, 23, 58, 28, 00, 00]",0,"[twitter, android]","[bbc, care, much, human, right, homosexual, ri...",[negative]

In [26]:
# Join tokens for all string columns
for col in worldcup2022.select_dtypes(include='str').columns:
    worldcup2022[col] = worldcup2022[col].apply(lambda x: ' '.join(x) if isinstance(x, list) else x)

In [27]:
worldcup2022.head(5)

,Unnamed: 0,Date Created,Number of Likes,Source of Tweet,Tweet,Sentiment
0,0,2022 11 20 23 59 21 00 00,4,twitter web app,drinking today worldcup2022,neutral
1,1,2022 11 20 23 59 01 00 00,3,twitter iphone,amazing worldcup2022 launch video show much fa...,positive
2,2,2022 11 20 23 58 41 00 00,1,twitter iphone,worth reading watching worldcup2022,positive
3,3,2022 11 20 23 58 33 00 00,1,twitter web app,golden maknae shinning bright jeonjungkook jun...,positive
4,4,2022 11 20 23 58 28 00 00,0,twitter android,bbc care much human right homosexual right wom...,negative

In [30]:
#save the preprocessed worldcup2022
worldcup2022.to_csv(r"C:\Projects\worldcup-social-media-nlp\Data\Preprocessed_Data\worldcup2022.csv")